### ISSUE TITLE
Fix dark mode

### ISSUE THREAD

**Issue by Amritanshu02** [Amritanshu02/NotesWebsite#21]
Dark mode not working.

**Comment by MufaddalHakim** [comment]
I want to do it. Please assign me.

**Comment by Amritanshu02** [comment]
Go ahead

**Comment by Amritanshu02** [comment]
Also if you can, change the position of the button of dark mode and place it in the navbar

**Comment by MufaddalHakim** [comment]
Okay I'll do it

**Comment by MufaddalHakim** [comment]
Hey! dark mode seems to be working for me. What's the problem exactly that you're facing?

**Comment by Amritanshu02** [comment]
> Hey! dark mode seems to be working for me. What's the problem exactly that you're facing?

Yes, I had reverted some merges that why now it is working properly.

**Comment by MufaddalHakim** [comment]
Ok I'll still go on and change the button location and make some minor tweaks

**Comment by Amritanshu02** [comment]
That would be great. Go ahead.

**Comment by MufaddalHakim** [comment]
Hello, the dark mode currently implemented uses darkmode.js library which comes with the button, and its styling. So the button position cannot be changed unless we implement our own dark mode function.

**Comment by Amritanshu02** [comment]
That's your call now, if you want to still do it, you could make a PR and I will see what to do with it. Else you could create your own issue. Happy hacking :)
